name: calender_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - aiofiles==23.2.1
    - aiohttp==3.9.5
    - aiohttp-socks==0.7.1
    - icalendar==5.0.13
    - matrix-nio==0.23.0
    - python-dotenv==1.0.1
    - requests==2.32.3
    - zulip==0.9.0
    - python-dateutil==2.9.0
