name: Run the bot daily at 9:00 AM IST/3:30 AM UTC

on:
  schedule:
    - cron: '30 3 * * *'  # This is 3:30 AM UTC, which is 9:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        source $HOME/miniconda/bin/activate
        conda init bash
        conda config --set always_yes yes --set changeps1 no

    - name: Create Conda environment
      run: |
        source $HOME/miniconda/bin/activate
        conda env create -f environment.yml
      
    - name: Activate environment and install dependencies
      run: |
        source $HOME/miniconda/bin/activate calender_bot
        conda list

    - name: Create temporary .env file
      run: |
        echo "ICAL_URL=${{ secrets.ICAL_URL }}" >> .env
        echo "ZULIP_API_KEY=${{ secrets.ZULIP_API_KEY }}" >> .env
        echo "ZULIP_EMAIL=${{ secrets.ZULIP_EMAIL }}" >> .env
        echo "ZULIP_SITE=${{ secrets.ZULIP_SITE }}" >> .env
      shell: bash
    
    - name: Run the bot
      run: |
        source $HOME/miniconda/bin/activate calender_bot
        python ical_to_zulip.py
    
    - name: Clean up .env file
      if: always()
      run: rm -f .env
