name: Run the bot daily at 9:00 AM IST/3:30 AM UTC

on:
  schedule:
    - cron: '30 3 * * *'  # This is 3:30 AM UTC, which is 9:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.12
        activate-environment: calender_bot
        environment-file: environment.yml
        auto-activate-base: false

    - name: Conda info
      shell: bash -l {0}
      run: conda info

    - name: Update environment if it exists, create if it doesn't
      shell: bash -l {0}
      run: |
        if conda env list | grep -q calender_bot; then
          echo "Updating existing environment"
          conda env update --name calender_bot --file environment.yml --prune
        else
          echo "Creating new environment"
          conda env create -f environment.yml
        fi

    - name: Activate environment
      shell: bash -l {0}
      run: conda activate calender_bot

    - name: Conda list
      shell: bash -l {0}
      run: conda list

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_ICAL_URL: ${{ secrets.ICAL_URL }}
        envkey_ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
        envkey_ZULIP_EMAIL: ${{ secrets.ZULIP_EMAIL }}
        envkey_ZULIP_SITE: ${{ secrets.ZULIP_SITE }}
        file_name: .env
        fail_on_empty: true
    
    - name: Run the bot
      shell: bash -l {0}
      run: |
        conda activate calender_bot
        python bot.py
