name: Run the bot daily at 9:00 AM IST/3:30 AM UTC

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: calender_bot
        environment-file: environment.yml
          
    - name: Install dependencies with anaconda
      run: |
        conda env create -f environment.yml
        conda activate calender_bot
    
    # - name: Create .env file
    #   uses: SpicyPizza/create-envfile@v2.0
    #   with:
    #     envkey_ICAL_URL: ${{ secrets.ICAL_URL }}
    #     envkey_ZULIP_API_KEY: ${{ secrets.ZULIP_API_KEY }}
    #     envkey_ZULIP_EMAIL: ${{ secrets.ZULIP_EMAIL }}
    #     envkey_ZULIP_SITE: ${{ secrets.ZULIP_SITE }}
    #     file_name: .env
    #     fail_on_empty: true